### ISSUE TITLE
Ability to interact with survey

### ISSUE THREAD

**Issue by perzizzle** [ansible/tower-cli#39] opened 2015-02-25 21:29 UTC
It would be useful to be able to launch a job that has surveys configured for it. Something to the effect of tower-cli job launch --job-template 111 --survey env=production.

In this example, job-template 111 will have a set of extra_vars defined and a survey question that has a list of environments available as radio buttons. I don't want to have to pass in a file with all the extra_vars, I just want to "answer" the survey (or overwrite what env is defined as in the extra_vars)

**Comment by mtotheikle** [comment] 2015-05-27 07:20
+1

**Comment by tristanbes** [comment] 2015-06-01 16:39
+1

**Comment by tomfotherby** [comment] 2015-09-21 10:52
+1 

We've been migrating our scripts so instead of deploying HEAD, we now deploy a particular `build_num`. The build_num is entered using a survey in Ansible Tower when doing a manual deployment. The problem is that our automatic builds no longer work because we need to pass in the build_num via `tower-cli`

I did notice we can pass the variable we need from the survey like this:

    root@3ab86751d116:/# echo "version: 157" > /tmp/extra_vars.yml                                                                                                                                          
    root@3ab86751d116:/# tower-cli job launch --job-template=48 --extra-vars=/tmp/extra_vars.yml

*but* this clobbers the other variables set up via the Tower job template.

**Comment by AlanCoding** [comment] 2015-10-23 13:45
There's a deeper problem with tower-cli options for surveys - there basically are none. After doing some testing of problems that @simfarm discovered, I realized that even if the job template sets `ask_variables_on_launch=true`, then it will show the existing extra_vars for that template. Survey variables don't get added to the list which is presented to the user. You have to know the survey variable names in advance (basically defeating the point of a survey). There is no way to view the survey questions in tower-cli, and including them would require additional navigation of the job template endpoints.

We could still use the existing structure of a click.edit() text input in a job launch. It would be straightforward to navigate the API endpoints go gather the survey questions and variable defaults. Then leave the questions as comments. I think users would still prefer an editable text area over a linear question/answer structure (although it would be good to get feedback on this). I would rank this as a top priority for a 2.4.0 release.

**Comment by tomfotherby** [comment] 2015-10-23 14:09
> although it would be good to get feedback on this

In my case, I didn't need to interact with the survey, I just needed to pass some variables I knew were needed by the survey, so v.2.3.0 solves the issue from me.

**Comment by perzizzle** [comment] 2015-10-23 15:43
In my specific use case I am running tower-cli from jenkins so I need a way to answer the survey but I don't want to do it interactively.  I know the questions being asked beforehand. But, I can also see the desire to have tower-cli ask each survey question when run from the command line. This is a lower priority for me.

**Comment by ryanooi** [comment] 2016-01-12 07:31
+1

**Comment by jangsutsr** [comment] 2017-03-08 19:24
Survey feature is added to 3.1 release. Closing this issue.

**Closed by jangsutsr** 2017-03-08 19:24 UTC
Labels: needs_devel, P4
